/**
 * @file index.js
 * @author liunannan
 * @date 2026-09-13
 * @description 前后端共用错误码与 SSE 事件名（纯 JS，非 TS-only）
 */

const ERROR_CODES = Object.freeze({
  AUTH_INVALID: 'AUTH_INVALID',
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  AUTH_EXPIRED: 'AUTH_EXPIRED',
  AUTH_USERNAME_TAKEN: 'AUTH_USERNAME_TAKEN',
  AUTH_PASSWORD_MISMATCH: 'AUTH_PASSWORD_MISMATCH',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  CONVERSATION_NOT_FOUND: 'CONVERSATION_NOT_FOUND',
  CONVERSATION_BUSY: 'CONVERSATION_BUSY',
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  QIANFAN_TIMEOUT: 'QIANFAN_TIMEOUT',
  QIANFAN_RATE_LIMIT: 'QIANFAN_RATE_LIMIT',
  QIANFAN_CONTENT_FILTER: 'QIANFAN_CONTENT_FILTER',
  QIANFAN_ERROR: 'QIANFAN_ERROR',
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',
});

const SSE_EVENTS = Object.freeze({
  META: 'meta',
  DELTA: 'delta',
  DONE: 'done',
  ERROR: 'error',
});

module.exports = {
  ERROR_CODES,
  SSE_EVENTS,
};
