/**
 * @file index.mjs
 * @author liunannan
 * @date 2026-09-14
 * @description ESM 导出，供 Vite；内容与 index.js 保持一致
 */

export const ERROR_CODES = Object.freeze({
  AUTH_INVALID: 'AUTH_INVALID',
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  AUTH_EXPIRED: 'AUTH_EXPIRED',
  AUTH_USERNAME_TAKEN: 'AUTH_USERNAME_TAKEN',
  AUTH_PASSWORD_MISMATCH: 'AUTH_PASSWORD_MISMATCH',
  AUTH_RATE_LIMITED: 'AUTH_RATE_LIMITED',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  CONVERSATION_NOT_FOUND: 'CONVERSATION_NOT_FOUND',
  CONVERSATION_BUSY: 'CONVERSATION_BUSY',
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  QIANFAN_TIMEOUT: 'QIANFAN_TIMEOUT',
  QIANFAN_RATE_LIMIT: 'QIANFAN_RATE_LIMIT',
  QIANFAN_CONTENT_FILTER: 'QIANFAN_CONTENT_FILTER',
  QIANFAN_ERROR: 'QIANFAN_ERROR',
  CLIENT_ABORTED: 'CLIENT_ABORTED',
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',
});

export const SSE_EVENTS = Object.freeze({
  META: 'meta',
  DELTA: 'delta',
  DONE: 'done',
  ERROR: 'error',
});

export const CONTEXT_MAX_MESSAGES = 20;
