export const ERROR_CODES: {
  readonly AUTH_INVALID: 'AUTH_INVALID';
  readonly AUTH_REQUIRED: 'AUTH_REQUIRED';
  readonly AUTH_EXPIRED: 'AUTH_EXPIRED';
  readonly AUTH_USERNAME_TAKEN: 'AUTH_USERNAME_TAKEN';
  readonly VALIDATION_ERROR: 'VALIDATION_ERROR';
  readonly CONVERSATION_NOT_FOUND: 'CONVERSATION_NOT_FOUND';
  readonly CONVERSATION_BUSY: 'CONVERSATION_BUSY';
  readonly INTERNAL_ERROR: 'INTERNAL_ERROR';
  readonly QIANFAN_TIMEOUT: 'QIANFAN_TIMEOUT';
  readonly QIANFAN_RATE_LIMIT: 'QIANFAN_RATE_LIMIT';
  readonly QIANFAN_CONTENT_FILTER: 'QIANFAN_CONTENT_FILTER';
  readonly QIANFAN_ERROR: 'QIANFAN_ERROR';
  readonly NOT_IMPLEMENTED: 'NOT_IMPLEMENTED';
};

export const SSE_EVENTS: {
  readonly META: 'meta';
  readonly DELTA: 'delta';
  readonly DONE: 'done';
  readonly ERROR: 'error';
};
